### ISSUE TITLE
I can create blank contacts

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Contacts#1]
I'm able to create contacts without any info about the name, company or data.

![contactos](https://cloud.githubusercontent.com/assets/1384919/8804802/3324567c-2fce-11e5-895d-bdf2bec4bde7.PNG)

**Comment by Robby2023** [comment]
In my opinion the name should be required, other data can be optional.

**Comment by Navas23** [comment]
Solved here: https://github.com/Inevio/Contacts/commit/0406b7c4e8ff077a00a85e7f478e7b843353b7a6
