### ISSUE TITLE
Changing selected contact while on edit mode

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Contacts#10]
When you click "Edit contact" and enter edit mode, if you click on another contact, you change all the info to the new contact while maintaining edit mode. Is it working correctly or should we leave edit mode when switching the selected contact?

How to emulate:
1 - Click on a contact
2 - Click on "Edit contact"
3 - Click on a different contact
4 - Edit mode continues activated

**Comment by jorge9200** [comment]
First version blocks changing contact while editing mode
