### ISSUE TITLE
Generated avatar empty in companies

### ISSUE THREAD

**Issue by javiergarmon** [Inevio/Contacts#16]
As you can see, companies have an empty avatar.
<img width="612" alt="screen shot 2015-12-13 at 13 49 49" src="https://cloud.githubusercontent.com/assets/1794673/11767046/819e152e-a1a0-11e5-9213-590ebe5d591d.png">

Also we can add a background watermark under the avatar letters when the contact is a company, something similar to what Apple Contacts does.
<img width="355" alt="screen shot 2015-12-13 at 13 52 12" src="https://cloud.githubusercontent.com/assets/1794673/11767054/be7ad0b8-a1a0-11e5-91e3-d7ee3bce7f89.png">

**Comment by jorge9200** [comment]
fixed
