### ISSUE TITLE
New lines forgotten in notes

### ISSUE THREAD

**Issue by javiergarmon** [Inevio/Contacts#18]
In the normal view (no edition) of a contact the new lines aren't displayed. Red lines represent the expected new lines.

![screen shot 2015-12-13 at 17 19 47](https://cloud.githubusercontent.com/assets/1794673/11767959/93876452-a1be-11e5-9427-ce97a96b349c.png)

Probably you can fix it appending a `.replace( /\\n/g, '<br/>' )` to the variable wich contains the texts when you append the text to the DOM.

**Comment by jorge9200** [comment]
fixed
