### ISSUE TITLE
Dropdown sometimes doesn't close

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Contacts#22]
When you click on the "plus" on Telephone, Mail or Address to add info, a dropdown appears and when you click outside the dropdown it closes (good).

However, if you click on another "plus" while having the dropdown opened, it opens the new dropdown without closing the old one.

![popup](https://cloud.githubusercontent.com/assets/1384919/11808154/010af942-a31f-11e5-9687-bc4376b96845.PNG)

**Comment by jorge9200** [comment]
fixed
