### ISSUE TITLE
Contact is deleted when clicking on cancel button

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Contacts#25]
When you start creating a new contact and you fill some inputs, if you click "save" button but you haven't added a Name or a Company, a popup appears asking if you want to create an empty contact.

If you click cancel, the contact is removed, deleting all the info you've added. Clicking cancel should take you back to edit mode so you can add a Name to the contact.

**Comment by jorge9200** [comment]
fixed, now the alert only appears when you haven't write anything
