### ISSUE TITLE
Info is not selectable

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Contacts#26]
If I want to copy some info from a contact (Telephone, Email, Address...) I cant, the info is not selectable. It would be useful if we could make info selectable because maybe you want to copy the email address from someone to send him an email for example.

Adding the class "wz-selectable" to the span should be enough

**Comment by Robby2023** [comment]
Adding the class "wz-selectable" to the span should be enough

**Comment by jorge9200** [comment]
fixed
