### ISSUE TITLE
Misalignment on elements

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Contacts#3]
Inside the Info tab, the elements under the Phone section are misaligned.

![alignment](https://cloud.githubusercontent.com/assets/1384919/8805409/568fb432-2fd1-11e5-9276-f7486610db03.PNG)

**Comment by Navas23** [comment]
Fixed here https://github.com/Inevio/Contacts/commit/d0f9438132d2160f8f9da700136aa958ef52edc0
