### ISSUE TITLE
Sometimes uppercase and sometimes not inside Phone section 

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Contacts#4]
![mayus](https://cloud.githubusercontent.com/assets/1384919/8805458/a2424782-2fd1-11e5-8350-663bfe07e903.PNG)

mobile vs Mobile
home phone vs Home phone

**Comment by Navas23** [comment]
Fixed here https://github.com/Inevio/Contacts/commit/3da5d2474bdde70622116acd91c89f9f9d26b9c5
