### ISSUE TITLE
I can save empty entries inside Info tab

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Contacts#5]
Entries are saved although empty:

![empty](https://cloud.githubusercontent.com/assets/1384919/8805564/324d1e56-2fd2-11e5-832c-babd947986d3.PNG)

**Comment by Navas23** [comment]
Solved https://github.com/Inevio/Contacts/commit/0406b7c4e8ff077a00a85e7f478e7b843353b7a6

**Comment by Navas23** [comment]
Fixed here https://github.com/Inevio/Contacts/commit/f307a498a0e1dc298ac14a9014f0093ee8c7fa6f
