### ISSUE TITLE
No padding on inputs when writing info

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Contacts#6]
There is no padding at all on the inputs when editing data

![padding](https://cloud.githubusercontent.com/assets/1384919/8805700/fd1955a0-2fd2-11e5-95ee-73133f186a06.PNG)

**Comment by Navas23** [comment]
Fixed here https://github.com/Inevio/Contacts/commit/27d29f1c13b05fde371335e6fef873fbadcedd66
