### ISSUE TITLE
Creating contacts without name or info

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Contacts#8]
You can create contacts without adding name, surname, company or any info whatsoever.

![vacio](https://cloud.githubusercontent.com/assets/1384919/11687615/f6b7a7a6-9e87-11e5-9646-f73cc3dc2443.PNG)

We should force to fill some fields before creating a contact.

**Comment by jorge9200** [comment]
standart permitts

**Comment by javiergarmon** [comment]
I'm sorry @Robby2023 but the standard allows it because the VCard file itself isn't empty. You can read more about the standard definition at https://tools.ietf.org/html/rfc6352

Maybe we should show a confirm dialog as Outlook does but always allow empty VCards.

**Comment by jorge9200** [comment]
fixed
